apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: bloodyturkey_iot
    user: bloodyturkey
    secureJsonData:
      password: bloodyturkey2026
    jsonData:
      sslmode: disable
