CREATE DATABASE IF NOT EXISTS bte_dev CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'bte'@'127.0.0.1' IDENTIFIED BY 'bte_dev_local';
GRANT ALL PRIVILEGES ON bte_dev.* TO 'bte'@'127.0.0.1';
FLUSH PRIVILEGES;